### ISSUE TITLE
ioutil.SectionWriter runtime error:slice bounds out of range 

### ISSUE THREAD

**Issue by robin11** [dsnet/golib#1]
hi ! I'm using the ioutil.SectionWriter to write to files at different offset concurently,but runtime error:slice bounds out of range raised. I'm confused if I used the wrong way?the code I used is as follows:
````
sectionWriter:=ioutil.NewSectionWriter(file,offset,num)
_,err=io.Copy(sectionWriter,resp.Body)
````
the error is as follows:
```
panic: runtime error: slice bounds out of range

goroutine 20 [running]:
panic(0x80f5a0, 0xc82001a0e0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/dsnet/golib/ioutil.(*SectionWriter).WriteAt(0xc820015a10, 0xc820130000, 0x8000, 0x8000, 0x80000000, 0xc82000b4c0, 0x0, 0x0)
        /home/robin/cold-storage/clients/cmd_go_lang/csutil/src/github.com/dsnet/golib/ioutil/section_writer.go:41 +0x21a
github.com/dsnet/golib/ioutil.(*SectionWriter).Write(0xc820015a10, 0xc820130000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/robin/cold-storage/clients/cmd_go_lang/csutil/src/github.com/dsnet/golib/ioutil/section_writer.go:27 +0x61
io.copyBuffer(0x7f88a4244ce8, 0xc820015a10, 0x7f88a41ff0b0, 0xc82000b500, 0xc820130000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/io/io.go:382 +0x2c9
io.Copy(0x7f88a4244ce8, 0xc820015a10, 0x7f88a41ff0b0, 0xc82000b500, 0xc82000b500, 0x0, 0x0)
        /usr/lib/go-1.6/src/io/io.go:350 +0x64
```
During the debug,I find that when the error happens,the cnt is much larger than the length of data slice.But I don't know how to solve it !Am I using it the wrong way?

**Comment by dsnet** [comment]
Hi @Robin11, thanks for your interest in this package. You seem to be using it the right way. I wouldn't be surprised if there's a bug in my implementation. Most of the code in the `golib` repository is pretty trashy and I'm not particularly proud of it. You'll even notice that most of the `ioutil` package lacks proper unit tests.

If you fix the bug, feel free to send a PR to fix it. Currently, I consider `golib` an unmaintained repo.
