### ISSUE TITLE
try: reconsider func names

### ISSUE THREAD

**Issue by josharian** [dsnet/golib#4]
I've been using try in scripts and really liking it.

However, I find A0, A1, etc to be fairly unintuitive. Particularly since in the kind of context in which I'm using try, I'm also tempted to dot import it. Then code reads:

```go
A0(fn())
```

and the A0 is mysterious.

I'm on board for them being short. But maybe E for error? H for handle? X for "danger I might panic"? C for check?

Also, I'd like to request just "A" instead of "A0". :)

**Comment by dsnet** [comment]
Done in https://github.com/dsnet/try/pull/1
